### PR TITLE
Extend game to 11:59:59 PM next Sunday.

### PR DESCRIPTION
**Pull request by wcarss**
For Mackenzie Bucks:

Why did the scarecrow win an award? Because he was outstanding in his field.
When asked how he accomplished this, he said, "Hay, it's in my jeans."

Anyway: let's keep playing. :)

### CODE REVIEW

**Comment by ekmccann** [comment]
Agree 2/2

**Comment by mimosacb** [comment]
Agreed 3/3

**Comment by stolksdorf** [comment]
Agreed 4/4. I like the language cleanup. Also, the two parter on that joke got me.

**Comment by DukeKataron** [comment]
Agree 5/5

**Comment by stolksdorf** [comment]
Rule has majority! Rule passes! Whew, just in time.

**Pull request merged**
