### PR TITLE
Comedy, Inspiration, and Noble Dogs

### PR DESCRIPTION
**Pull request by Meggeroni**
In your initial comment, leave your best quote or joke to earn a Mackenzie-Buck! At very least, these can be redeemed for Mackenzie cuddles, but they may be worth even more someday...?

Two blonds were walking in the forest, following some tracks, debating if the tracks were deer or moose. They wandered for hours by the tracks, trying to decide if it was a moose or a deer, until they were suddenly hit by the train.

### CODE REVIEW

**Comment by stolksdorf** [comment]
This is everything I want. I had high expectations for your first rule @Meggeroni, and my god did you deliver.

2/2 AGREED.

**Comment by lpellow** [comment]
Oh no I'm awful at jokes. Maybe I can just quote my patients.
Agreed 3/3

**Comment by stolksdorf** [comment]
Being a 200-level rule, it requires at least 30% of the votes to pass. We have 33%.

CONGRATS!

**Comment by stolksdorf** [comment]
> Though her joke is indeed funny, the rule change was not in effect when the pull request and comment were created, so no Mackenzie-Buck can be awarded.

-- The Arbiter

ALL HAIL

**Pull request merged**
