### PR TITLE
The Pip Shuffle

### PR DESCRIPTION
**Pull request by lpellow**
Turn order is shuffled according to point value at the end of each round.

### CODE REVIEW

**Comment by lpellow** [comment]
For M-B's: 
Are you the eroding joint cartilage that causes osteoarthritis?
.... Cause you got me weak in the knees ....

**Comment by ekmccann** [comment]
Approve 2/2

**Comment by JMTyler** [comment]
Agree 3/3

And Laura, Meg's rule asks for quotes or jokes, not foolproof pick-up lines!

**Comment by lpellow** [comment]
Technically it is both of those things.

**Comment by DukeKataron** [comment]
Agree 4/4

bananas

**Comment by mimosacb** [comment]
So it's like the Kansas City Shuffle except you go 'pip!' and I go 'pip!' and nobody has to die.
Approved. 5/5

**Comment by ktrain** [comment]
I love that everyone is more concerned with having things in the game named after them than with earning points.

**Comment by wcarss** [comment]
Agreed. 6/6.

**Comment by mimosacb** [comment]
LP's gonna get all dem points if this doesn't get merged soon. An interesting ambiguity is whether the vote ends as soon as we hit majority or when everyone has finished voting. Now that points are on the line I think it's more relevant.

**Comment by DukeKataron** [comment]
Yeah, we're gonna have to figure out how soon things get approved and merged otherwise people gonna be rollin' in points.

**Comment by stolksdorf** [comment]
Since this is a tier 100 rule, we need majority to pass. AND WE HAVE IT. It passes!

@mimosacb and @DukeKataron, my speed of moderation shouldn't effect game. That being said, everyone knows that her rule got approved at 5 votes, so now your are just throwing points at her :P

**Pull request merged**
