### PR TITLE
Rule tiers, Go!

### PR DESCRIPTION
**Pull request by stolksdorf**
Adding in the concept of rule tiers and different voting thresholds for each tier. 0th tier rules are harder to get passed, but will stick longer. 3rd tier rules come fast, leave fast (once we figure out what vetos are :P)

### CODE REVIEW

**Comment by JMTyler** [comment]
Yeah, I don't understand what "an eligible voter that has a veto" means.  Can you clarify?

Also, when you say 3rd tier rules "leave fast," really you mean they're most easily overridden by future 0-2 tier rules, **assuming any future rules actually conflict with them**.  If no future rules conflict, then the 3rd tier rules stick around for forever just as much as 0th tier rules.

If I were going to propose a 2nd tier rule to conflict with / override an existing 3rd tier rule, why wouldn't I instead just re-write the 3rd tier rule so I don't have to worry about the voters?

**Comment by stolksdorf** [comment]
"an eligible voter that has a veto" means literally what it says. Currently no one has a 'veto' and there's no way to earn any **yet**. Therefore it's impossible to pass tier 300 rules currently (if this passes). I left it open for someone to play with.

"leave fast' meant it takes very few people to edit or remove a tier 300 rule.

**Comment by DukeKataron** [comment]
Not sure how I feel about the rule change itself, but I do love the name of the rule

**Comment by mimosacb** [comment]
Agreed. 1/1
https://www.youtube.com/v/FlTIk80uBPg?version=3&start=221&end=223&autoplay=1&hl=en_US&rel=0

**Comment by wcarss** [comment]
Agreed. 3/3 (counting scott's proposal as an agree vote -- this follows the example in how2play.md)

**Comment by DukeKataron** [comment]
Agreed 4/4

This rule frightens me, but I am easily frightened so I will not let that scare me off

**Comment by Meggeroni** [comment]
Agreed 5/5 

Neat! I love cake.

**Comment by robee** [comment]
Agreed 6/6

**Comment by JMTyler** [comment]
Agreed 7/7

**Comment by lpellow** [comment]
Agreed 8/8
Sorry for the delayyyy. LP's next rule will be if LP doesn't comment in 48 hours, doesn't get a vote :P

**Comment by stolksdorf** [comment]
Ping @McCsocks

**Comment by stolksdorf** [comment]
@McCsocks is currently out of internet range, but she's contacted me to let me know that she votes 'Agreed" on this change. 

Proof

AGREED 9/9. Rule passes!

**Pull request merged**
