### PR TITLE
Meritocracy & Risk

### PR DESCRIPTION
**Pull request by JMTyler**
This change earns you more points if you propose favourable rules.  It also encourages risk -- proposing lower-tier rules is likely to reward you with more points.

### CODE REVIEW

**Comment by stolksdorf** [comment]
Very elegant way of rewarding points. 

My only fear is that awarding the random points after the voting means the voters will know how many points you will earn before you earn them. I'm not sure if this will impact anything, but something to be aware about.

**Comment by JMTyler** [comment]
I agree that it's something to be aware of, but I don't think it really affects anything substantial (yet, at least).  Even if they downvote your proposal into oblivion, that doesn't stop you from earning the points.  In a sense it's not really different at all.

**Comment by Meggeroni** [comment]
Oh weird. I actually thought that if your rule didn't pass, you wouldn't get your points. Now that I re-read, it doesn't say that at all. (Obviously not a programmer...)

**Comment by mimosacb** [comment]
I endorse this message.
2/2
Would approve again.

**Comment by DukeKataron** [comment]
Agree 3/3. Thanks for not immediately trying to kill me off and assume my title.

**Comment by ekmccann** [comment]
Agree 4/4.

**Comment by stolksdorf** [comment]
Even though I have reservations, I like this more than I don't like it. 

Agreed 5/5. We have majority, rule passes!

**Comment by stolksdorf** [comment]
There is ambiguity over that when @JMTyler's rule passes, does he get the additional points or not (since the rule itself changes the structure of the turn). We will be calling in our Arbiter, @ktrain, to decide. I'll merge in the rule when he makes his decision.

**Comment by Meggeroni** [comment]
Hmm. I interpreted it that he wouldn't get the points.
1. Proposes his rule
2. Calculates points
3. Then rule is voted on and passes/fails. (This is when Jared's changes would take effect, after his points are calculated in 2.)

@ktrain 's call either way!

**Comment by ktrain** [comment]
As @Meggeroni said, the current rule definition states that the points are calculated and awarded before @JMTyler's rule change takes effect, so he does not get the extra points.

**Pull request merged**
