### PR TITLE
Grand Admiralty Rule

### PR DESCRIPTION
**Pull request by DukeKataron**
I have no actual things to change at this time, so I'm going with this instead. GRAND ADMIRAL DUKEKATARON.

### CODE REVIEW

**Comment by stolksdorf** [comment]
AGREED 2/2. Fuck it, why not.

**Comment by wcarss** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

agreed: 3/3.

**Comment by JMTyler** [comment]
Agreed 4/4

Now I just need to find a way to lure you into glorious battle...

**Comment by DukeKataron** [comment]
Wyatt, I appreciate that you think me clever enough to have set up some sort of trap. I just really like titles. And the other rule I have in mind involves gambling points, and folk just don't have enough points yet to make that worthwhile.

AND JARED, ALL MY BATTLES ARE GLORIOUS PEW PEW PEW LASERS AND SUCH

**Comment by DukeKataron** [comment]
Good news, everyone! I am a human again! I have surrounded my metal bones with warm, meaty flesh, and all is well once more.

**Comment by lpellow** [comment]
I love that this is a level 100 rule. Agreed, 5/5.

**Comment by stolksdorf** [comment]
Since it is a tier 100 rule, and we have majority, the rule passes. Congrats to Grand Admiral @DukeKataron,

**Pull request merged**
